spring.application.name=Customer Segmentation and Sales Forecasting for E-Commerce

spring.datasource.url=jdbc:postgresql://localhost:5432/customersegmentation
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
